version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME:-tire_services_mysql}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-tire_services}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - tire_services_network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (для удобства управления БД)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${PHPMYADMIN_CONTAINER_NAME:-tire_services_phpmyadmin}
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      - mysql
    networks:
      - tire_services_network

  

volumes:
  mysql_data:
    driver: local

networks:
  tire_services_network:
    driver: bridge 